export type Location = { city: string; country: string };

const LOCATIONS: Location[] = [
  // Africa
  { city: 'Johannesburg', country: 'South Africa' },
  { city: 'Cape Town', country: 'South Africa' },
  { city: 'Durban', country: 'South Africa' },
  { city: 'Pretoria', country: 'South Africa' },
  { city: 'Port Elizabeth', country: 'South Africa' },
  { city: 'Lagos', country: 'Nigeria' },
  { city: 'Abuja', country: 'Nigeria' },
  { city: 'Port Harcourt', country: 'Nigeria' },
  { city: 'Kano', country: 'Nigeria' },
  { city: 'Accra', country: 'Ghana' },
  { city: 'Tema', country: 'Ghana' },
  { city: 'Nairobi', country: 'Kenya' },
  { city: 'Mombasa', country: 'Kenya' },
  { city: 'Dar es Salaam', country: 'Tanzania' },
  { city: 'Zanzibar', country: 'Tanzania' },
  { city: 'Addis Ababa', country: 'Ethiopia' },
  { city: 'Cairo', country: 'Egypt' },
  { city: 'Alexandria', country: 'Egypt' },
  { city: 'Port Said', country: 'Egypt' },
  { city: 'Casablanca', country: 'Morocco' },
  { city: 'Tangier', country: 'Morocco' },
  { city: 'Abidjan', country: 'Ivory Coast' },
  { city: 'Dakar', country: 'Senegal' },
  { city: 'Douala', country: 'Cameroon' },
  { city: 'Luanda', country: 'Angola' },
  { city: 'Maputo', country: 'Mozambique' },
  { city: 'Beira', country: 'Mozambique' },
  { city: 'Lusaka', country: 'Zambia' },
  { city: 'Harare', country: 'Zimbabwe' },
  { city: 'Gaborone', country: 'Botswana' },
  { city: 'Windhoek', country: 'Namibia' },
  { city: 'Walvis Bay', country: 'Namibia' },
  { city: 'Port Louis', country: 'Mauritius' },
  { city: 'Antananarivo', country: 'Madagascar' },
  { city: 'Toamasina', country: 'Madagascar' },
  { city: 'Kigali', country: 'Rwanda' },
  { city: 'Kampala', country: 'Uganda' },
  { city: 'Cotonou', country: 'Benin' },
  { city: 'Lomé', country: 'Togo' },
  { city: 'Conakry', country: 'Guinea' },
  { city: 'Freetown', country: 'Sierra Leone' },
  { city: 'Mogadishu', country: 'Somalia' },
  // Asia
  { city: 'Shanghai', country: 'China' },
  { city: 'Shenzhen', country: 'China' },
  { city: 'Guangzhou', country: 'China' },
  { city: 'Beijing', country: 'China' },
  { city: 'Tianjin', country: 'China' },
  { city: 'Qingdao', country: 'China' },
  { city: 'Ningbo', country: 'China' },
  { city: 'Xiamen', country: 'China' },
  { city: 'Wuhan', country: 'China' },
  { city: 'Chengdu', country: 'China' },
  { city: 'Hong Kong', country: 'Hong Kong' },
  { city: 'Busan', country: 'South Korea' },
  { city: 'Seoul', country: 'South Korea' },
  { city: 'Incheon', country: 'South Korea' },
  { city: 'Tokyo', country: 'Japan' },
  { city: 'Yokohama', country: 'Japan' },
  { city: 'Osaka', country: 'Japan' },
  { city: 'Nagoya', country: 'Japan' },
  { city: 'Kobe', country: 'Japan' },
  { city: 'Singapore', country: 'Singapore' },
  { city: 'Kuala Lumpur', country: 'Malaysia' },
  { city: 'Port Klang', country: 'Malaysia' },
  { city: 'Penang', country: 'Malaysia' },
  { city: 'Bangkok', country: 'Thailand' },
  { city: 'Laem Chabang', country: 'Thailand' },
  { city: 'Ho Chi Minh City', country: 'Vietnam' },
  { city: 'Hanoi', country: 'Vietnam' },
  { city: 'Hai Phong', country: 'Vietnam' },
  { city: 'Jakarta', country: 'Indonesia' },
  { city: 'Surabaya', country: 'Indonesia' },
  { city: 'Medan', country: 'Indonesia' },
  { city: 'Manila', country: 'Philippines' },
  { city: 'Cebu', country: 'Philippines' },
  { city: 'Mumbai', country: 'India' },
  { city: 'Chennai', country: 'India' },
  { city: 'Kolkata', country: 'India' },
  { city: 'Delhi', country: 'India' },
  { city: 'Nhava Sheva', country: 'India' },
  { city: 'Mundra', country: 'India' },
  { city: 'Colombo', country: 'Sri Lanka' },
  { city: 'Karachi', country: 'Pakistan' },
  { city: 'Lahore', country: 'Pakistan' },
  { city: 'Dhaka', country: 'Bangladesh' },
  { city: 'Chittagong', country: 'Bangladesh' },
  { city: 'Yangon', country: 'Myanmar' },
  { city: 'Taipei', country: 'Taiwan' },
  { city: 'Kaohsiung', country: 'Taiwan' },
  // Middle East
  { city: 'Dubai', country: 'United Arab Emirates' },
  { city: 'Abu Dhabi', country: 'United Arab Emirates' },
  { city: 'Sharjah', country: 'United Arab Emirates' },
  { city: 'Jebel Ali', country: 'United Arab Emirates' },
  { city: 'Jeddah', country: 'Saudi Arabia' },
  { city: 'Riyadh', country: 'Saudi Arabia' },
  { city: 'Dammam', country: 'Saudi Arabia' },
  { city: 'Doha', country: 'Qatar' },
  { city: 'Kuwait City', country: 'Kuwait' },
  { city: 'Muscat', country: 'Oman' },
  { city: 'Salalah', country: 'Oman' },
  { city: 'Manama', country: 'Bahrain' },
  { city: 'Beirut', country: 'Lebanon' },
  { city: 'Amman', country: 'Jordan' },
  // Europe
  { city: 'Rotterdam', country: 'Netherlands' },
  { city: 'Amsterdam', country: 'Netherlands' },
  { city: 'Antwerp', country: 'Belgium' },
  { city: 'Brussels', country: 'Belgium' },
  { city: 'Hamburg', country: 'Germany' },
  { city: 'Bremen', country: 'Germany' },
  { city: 'Frankfurt', country: 'Germany' },
  { city: 'Munich', country: 'Germany' },
  { city: 'London', country: 'United Kingdom' },
  { city: 'Felixstowe', country: 'United Kingdom' },
  { city: 'Southampton', country: 'United Kingdom' },
  { city: 'Liverpool', country: 'United Kingdom' },
  { city: 'Le Havre', country: 'France' },
  { city: 'Paris', country: 'France' },
  { city: 'Marseille', country: 'France' },
  { city: 'Lyon', country: 'France' },
  { city: 'Barcelona', country: 'Spain' },
  { city: 'Valencia', country: 'Spain' },
  { city: 'Algeciras', country: 'Spain' },
  { city: 'Madrid', country: 'Spain' },
  { city: 'Genoa', country: 'Italy' },
  { city: 'Naples', country: 'Italy' },
  { city: 'Milan', country: 'Italy' },
  { city: 'Rome', country: 'Italy' },
  { city: 'La Spezia', country: 'Italy' },
  { city: 'Piraeus', country: 'Greece' },
  { city: 'Athens', country: 'Greece' },
  { city: 'Thessaloniki', country: 'Greece' },
  { city: 'Lisbon', country: 'Portugal' },
  { city: 'Sines', country: 'Portugal' },
  { city: 'Porto', country: 'Portugal' },
  { city: 'Gdansk', country: 'Poland' },
  { city: 'Warsaw', country: 'Poland' },
  { city: 'Gothenburg', country: 'Sweden' },
  { city: 'Stockholm', country: 'Sweden' },
  { city: 'Copenhagen', country: 'Denmark' },
  { city: 'Aarhus', country: 'Denmark' },
  { city: 'Oslo', country: 'Norway' },
  { city: 'Helsinki', country: 'Finland' },
  { city: 'Zurich', country: 'Switzerland' },
  { city: 'Geneva', country: 'Switzerland' },
  { city: 'Vienna', country: 'Austria' },
  { city: 'Constanta', country: 'Romania' },
  { city: 'Bucharest', country: 'Romania' },
  { city: 'Istanbul', country: 'Turkey' },
  { city: 'Mersin', country: 'Turkey' },
  { city: 'Izmir', country: 'Turkey' },
  { city: 'Odessa', country: 'Ukraine' },
  { city: 'Kyiv', country: 'Ukraine' },
  { city: 'St Petersburg', country: 'Russia' },
  { city: 'Moscow', country: 'Russia' },
  { city: 'Vladivostok', country: 'Russia' },
  // Americas
  { city: 'New York', country: 'United States' },
  { city: 'Los Angeles', country: 'United States' },
  { city: 'Long Beach', country: 'United States' },
  { city: 'Miami', country: 'United States' },
  { city: 'Houston', country: 'United States' },
  { city: 'Seattle', country: 'United States' },
  { city: 'New Orleans', country: 'United States' },
  { city: 'Savannah', country: 'United States' },
  { city: 'Baltimore', country: 'United States' },
  { city: 'Chicago', country: 'United States' },
  { city: 'Vancouver', country: 'Canada' },
  { city: 'Toronto', country: 'Canada' },
  { city: 'Montreal', country: 'Canada' },
  { city: 'Halifax', country: 'Canada' },
  { city: 'Mexico City', country: 'Mexico' },
  { city: 'Veracruz', country: 'Mexico' },
  { city: 'Manzanillo', country: 'Mexico' },
  { city: 'Panama City', country: 'Panama' },
  { city: 'Colon', country: 'Panama' },
  { city: 'Bogotá', country: 'Colombia' },
  { city: 'Cartagena', country: 'Colombia' },
  { city: 'Buenaventura', country: 'Colombia' },
  { city: 'Santos', country: 'Brazil' },
  { city: 'São Paulo', country: 'Brazil' },
  { city: 'Rio de Janeiro', country: 'Brazil' },
  { city: 'Itajaí', country: 'Brazil' },
  { city: 'Buenos Aires', country: 'Argentina' },
  { city: 'Rosario', country: 'Argentina' },
  { city: 'Santiago', country: 'Chile' },
  { city: 'Valparaíso', country: 'Chile' },
  { city: 'Lima', country: 'Peru' },
  { city: 'Callao', country: 'Peru' },
  // Oceania
  { city: 'Sydney', country: 'Australia' },
  { city: 'Melbourne', country: 'Australia' },
  { city: 'Brisbane', country: 'Australia' },
  { city: 'Fremantle', country: 'Australia' },
  { city: 'Adelaide', country: 'Australia' },
  { city: 'Auckland', country: 'New Zealand' },
  { city: 'Wellington', country: 'New Zealand' },
  { city: 'Christchurch', country: 'New Zealand' },
];

export async function searchLocations(query: string): Promise<Location[]> {
  // Simulate network latency
  await new Promise((r) => setTimeout(r, 80));

  const q = query.toLowerCase().trim();
  if (!q) return [];

  return LOCATIONS.filter(
    ({ city, country }) =>
      city.toLowerCase().includes(q) || country.toLowerCase().includes(q),
  ).slice(0, 8);
}
